version: '3.9'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    env_file:
      - .env
    environment:
      DEBUG: 'True'
      GRAPHIQL: 'True'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
  client:
    image: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      HOSTNAME: web
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 80:4200