version: '3.9'
services:
  web:
    image: web:lastest
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1s
      timeout: 2s
      retries: 5