# Generated by Django 3.1.4 on 2020-12-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('trades', '0001_initial'), ('trades', '0002_auto_20201219_1443'), ('trades', '0003_auto_20201219_1444'), ('trades', '0004_auto_20201219_1444')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticker',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('trade_class', models.CharField(choices=[('ST', 'Stock'), ('OP', 'Option')], max_length=2)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trades.exchange')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trades.ticker')),
            ],
            options={
                'db_table': 'trade',
            },
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(check=models.Q(action__in=['B', 'S']), name='trades_trade_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(check=models.Q(trade_class__in=['ST', 'OP']), name='trades_trade_trade_class_valid'),
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['created_date', 'last_modified_date', 'ticker']},
        ),
    ]
