# Generated by Django 3.1.4 on 2020-12-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-created_date']},
        ),
    ]
