# Generated by Django 3.1.4 on 2020-12-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20201219_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['created_date']},
        ),
    ]
